### ISSUE TITLE
`link` command should not execute `npm install` if it was done before

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo2js#38]
At the moment `link` command does check if `npm install` was already executed before. I can be implemented via checking where `package-lock.json` file exists.

**Comment by HaidarJbeily7** [comment]
@maxonfjvipon I think we need to close this issue

**Comment by maxonfjvipon** [comment]
@HaidarJbeily7 yes, thank you. Next time to close the issue automatically with PR merged you can write `Closes: #...` in PR comment (here `#...` is the number of the issue started with `#`)
